### ISSUE TITLE
Chart for hugo/jekyll maybe?

### ISSUE THREAD

**Issue by epogrebnyak** [nschloe/stargraph#80]
There are documentation engines, but one can also add static site generators. I got a list, can try a PR.

**Comment by nschloe** [comment]
Sure, why not. Suggestions for packages?

**Comment by epogrebnyak** [comment]
I was counting stars for ssg's here: https://github.com/epogrebnyak/ssg-dataset#dataset

Probsbly should exclude ones in documentation graph already.

**Comment by styfle** [comment]
There are a lot of static site generators listed here: http://staticgen.com

The github repo for each can be parsed from the `repo` section of each file in this directory: https://github.com/netlify/staticgen/tree/master/content/projects

**Comment by epogrebnyak** [comment]
So we are not adding a chart on ssg to README?
